# Generated by Django 5.2.5 on 2025-08-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='category',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('health', 'Health'), ('food', 'Food'), ('sustainability', 'Environmental Sustainability'), ('iot_ai', 'IoT/AI'), ('agriculture', 'Agriculture')], default='undefined', max_length=50),
        ),
        migrations.AddField(
            model_name='startup',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
