# Generated by Django 5.2.5 on 2025-08-21 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_startup_category_startup_domain_startup_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='domain',
        ),
    ]
