# Generated by Django 5.2.5 on 2025-08-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_remove_startup_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='info_img',
            field=models.ImageField(blank=True, null=True, upload_to='startups/info/'),
        ),
    ]
