# Generated by Django 5.2.5 on 2025-09-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('link', models.URLField(blank=True, help_text='Link to LinkedIn or other external page.')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags, e.g., #nanotechnology, #healthcare', max_length=200)),
                ('details_pdf', models.FileField(blank=True, help_text='Optional: Upload a PDF with more details.', null=True, upload_to='event_pdfs/')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
